### ISSUE TITLE
remove arresteddevops-specific stuff from hugo code for kubecast.com

### ISSUE THREAD

**Issue by bridgetkromhout** [Kubecast/kubecast.github.io#1]
Hi, folks!

I'm glad to see you cloned the ADO repo as we'd talked about in London. I can't submit a PR since it's a private repo, so please update things so it no longer has items specific to Arrested DevOps:
- You really shouldn't use our Google Analytics id: UA-45939822-1 (since that puts us in control of all our traffic data instead of you). That appears all over the place in the repo.
- You've got references to arresteddevops.com all over the place in the code.
- Your metadata lists my name and @mattstratton's on the hosts files (which is how my personal Google alert brought this to my attention). Those come from these fields in ours: https://github.com/arresteddevops/ado-hugo/blob/master/data/hosts/bkromhout.yml#L2 and https://github.com/arresteddevops/ado-hugo/blob/master/data/hosts/mstratton.yml#L2
- This is a Matt-specific page:
  https://github.com/Kubecast/kubecast.github.io/blob/master/matt/index.html
- These are also specific to us and are pointing at our site:
  https://github.com/Kubecast/kubecast.github.io/blob/master/bananastand/index.html
  https://github.com/Kubecast/kubecast.github.io/blob/master/guestform/index.html

I'm sure this is a work in progress, but let's get this fixed before you lose the chance to see all your own traffic stats from your exciting new podcast. :)

**Comment by mattstratton** [comment]
The GA thing is easy to fix, btw. It's a parameter in `config.toml`

**Comment by mattstratton** [comment]
I would encourage you to make the repo public (there shouldn't be anything in there that is "eyes only") so that we can help you clean it up - alternately, grant @mattstratton and @bridgetkromhout read access to the repo so we can submit PR's and help you clean it up :)

**Comment by ipedrazas** [comment]
@mattstratton @bridgetkromhout I've removed the google analytics code. It was hardcoded in a few pages.

I'm on the phone right now but I'll make public the repo (thought it was).

thanks for the heads up!

**Comment by ipedrazas** [comment]
I think I've fixed all the issues by now... phew! I might open a few issues in your [ado-hugo](https://github.com/arresteddevops/ado-hugo) project about the hardcoded ga key.

Thanks again!
